basePath: /storage
definitions:
  utils.ErrorCodeMessage:
    properties:
      code:
        type: string
      message:
        type: string
    type: object
  utils.TelarError:
    properties:
      error:
        $ref: '#/definitions/utils.ErrorCodeMessage'
    type: object
host: social.faas.telar.dev
info:
  contact:
    email: dev@telar.dev
    name: API Support
  description: This is an API to handle files
  license:
    name: MIT
    url: https://github.com/red-gold/telar-web/blob/master/LICENSE
  termsOfService: http://swagger.io/terms/
  title: Storage micro API
  version: "1.0"
paths:
  /{uid}/{dir}:
    post:
      consumes:
      - multipart/form-data
      description: Upload a file to the storage and return the download URL
      parameters:
      - default: Bearer <Add_token_here>
        description: Authentication
        in: header
        name: Authorization
        required: true
        type: string
      - description: User ID
        in: path
        name: uid
        required: true
        type: string
      - description: Directory name
        in: path
        name: dir
        required: true
        type: string
      - description: File to upload
        in: formData
        name: file
        required: true
        type: file
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            properties:
              payload:
                type: string
            type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/utils.TelarError'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/utils.TelarError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/utils.TelarError'
      security:
      - JWT: []
      summary: Upload a file to the storage
      tags:
      - upload
  /{uid}/{dir}/{name}:
    get:
      description: Download a file from the storage
      parameters:
      - default: Bearer <Add_token_here>
        description: Authentication
        in: header
        name: Authorization
        required: true
        type: string
      - description: Directory name
        in: path
        name: dir
        required: true
        type: string
      - description: File name
        in: path
        name: name
        required: true
        type: string
      - description: User ID
        in: path
        name: uid
        required: true
        type: string
      produces:
      - application/json
      responses:
        "302":
          description: Found
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/utils.TelarError'
      security:
      - JWT: []
      summary: Download a file from the storage
      tags:
      - download
securityDefinitions:
  JWT:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
