basePath: /circles
definitions:
  dto.Circle:
    properties:
      created_date:
        type: integer
      isSystem:
        type: boolean
      name:
        type: string
      objectId:
        type: string
      ownerUserId:
        type: string
    type: object
  models.CreateCircleModel:
    properties:
      name:
        type: string
    type: object
  utils.ErrorCodeMessage:
    properties:
      code:
        type: string
      message:
        type: string
    type: object
  utils.TelarError:
    properties:
      error:
        $ref: '#/definitions/utils.ErrorCodeMessage'
    type: object
host: social.faas.telar.dev
info:
  contact:
    email: dev@telar.dev
    name: API Support
  description: This is an API to handle user circles
  license:
    name: MIT
    url: https://github.com/red-gold/telar-web/blob/master/LICENSE
  termsOfService: http://swagger.io/terms/
  title: Circles micro API
  version: "1.0"
paths:
  /:
    post:
      consumes:
      - application/json
      description: Create a new circle with the given name
      parameters:
      - default: Bearer <Add_token_here>
        description: Authentication
        in: header
        name: Authorization
        required: true
        type: string
      - description: Create Circle Model
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/models.CreateCircleModel'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            properties:
              objectId:
                type: string
            type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/utils.TelarError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/utils.TelarError'
      security:
      - JWT: []
      summary: Create a new circle
      tags:
      - circles
    put:
      consumes:
      - application/json
      description: Update a circle by its ID
      parameters:
      - default: Bearer <Add_token_here>
        description: Authentication
        in: header
        name: Authorization
        required: true
        type: string
      - description: Circle object
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/dto.Circle'
      produces:
      - application/json
      responses:
        "200":
          description: Circle successfully updated
        "400":
          description: Invalid input data
          schema:
            $ref: '#/definitions/utils.TelarError'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/utils.TelarError'
      security:
      - JWT: []
      summary: Update a circle
      tags:
      - circles
  /{circleId}:
    delete:
      consumes:
      - application/json
      description: Delete a circle by id
      parameters:
      - default: Bearer <Add_token_here>
        description: Authentication
        in: header
        name: Authorization
        required: true
        type: string
      - description: Circle Id
        in: path
        name: circleId
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/utils.TelarError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/utils.TelarError'
      security:
      - JWT: []
      summary: Delete a circle
      tags:
      - circles
  /following/{userId}:
    post:
      consumes:
      - application/json
      description: Create a new following circle for a user
      parameters:
      - default: Bearer <Add_token_here>
        description: Authentication
        in: header
        name: Authorization
        required: true
        type: string
      - description: User Id
        in: path
        name: userId
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            properties:
              objectId:
                type: string
            type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/utils.TelarError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/utils.TelarError'
      security:
      - JWT: []
      summary: Create a new following circle
      tags:
      - circles
  /id/{circleId}:
    get:
      consumes:
      - application/json
      description: Get a circle by id
      parameters:
      - default: Bearer <Add_token_here>
        description: Authentication
        in: header
        name: Authorization
        required: true
        type: string
      - description: Circle Id
        in: path
        name: circleId
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.Circle'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/utils.TelarError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/utils.TelarError'
      security:
      - JWT: []
      summary: Get a circle
      tags:
      - circles
  /my:
    get:
      consumes:
      - application/json
      description: Get circles of the authenticated user
      parameters:
      - default: Bearer <Add_token_here>
        description: Authentication
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/dto.Circle'
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/utils.TelarError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/utils.TelarError'
      security:
      - JWT: []
      summary: Get my circles
      tags:
      - circles
securityDefinitions:
  JWT:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
